# Generated by Django 5.1.1 on 2024-09-26 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=6)),
                ('course_name', models.CharField(max_length=80)),
                ('course_detail', models.CharField(max_length=1000)),
                ('course_credit', models.IntegerField()),
                ('course_section', models.CharField(max_length=6)),
                ('course_remain', models.IntegerField(default=0)),
                ('full', models.BooleanField(default=False)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('year', models.CharField(max_length=4, null=True)),
                ('enrolled_students', models.ManyToManyField(blank=True, related_name='courses', to='quota.student')),
            ],
            options={
                'ordering': ['course_code'],
            },
        ),
    ]
