# Generated by Django 5.1.1 on 2024-09-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=6, unique=True)),
                ('course_name', models.CharField(max_length=80, unique=True)),
                ('course_detail', models.CharField(max_length=1000, unique=True)),
                ('course_credit', models.IntegerField()),
                ('course_section', models.CharField(max_length=6, unique=True)),
                ('course_remain', models.IntegerField(default=0)),
                ('Full', models.BooleanField(default=False)),
                ('semester', models.CharField(choices=[(1, '1'), (2, '2')], max_length=1)),
                ('year', models.CharField(max_length=4, unique=True)),
                ('student', models.ManyToManyField(blank=True, to='quota.student')),
            ],
            options={
                'ordering': ['course_code'],
            },
        ),
    ]
