# Generated by Django 5.1.1 on 2024-09-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quota', '0002_alter_student_username_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
