# Generated by Django 5.1.1 on 2024-09-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quota', '0004_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
    ]
