# Generated by Django 5.1.1 on 2024-09-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quota', '0006_alter_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_section',
            field=models.CharField(max_length=6),
        ),
    ]
